- id: foxylint-imports
  name: Import Modules not Names
  description: disallows the from_x_import_y import statement
  entry: foxylint-main imports
  language: python
  types: [python]
- id: foxylint-loggingcase
  name: Enforce lowercase logging
  description: do not capitalize sentences in log messages like you would in ordinary English
  entry: foxylint-main loggingcase
  language: python
  types: [python]
- id: yaml-not-yml
  name: YAML files must end with .yaml
  description: disallows the .yml suffix, allows only .yaml
  entry: foxylint-noyml
  language: python
  types: [file]
