- id: foxylint-imports
  name: Import Modules not Names
  description: disallows the from_x_import_y import statement
  entry: foxylint-imports
  language: python
  types: [python]
- id: yaml-not-yml
  name: YAML files must end with .yaml
  description: disallows the .yml suffix, allows only .yaml
  entry: foxylint-noyml
  language: python
  types: [file]
