# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
    args:
      - --line-length=150
      - --target-version=py311
      - --skip-string-normalization
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
    - id: flake8
      args:
        - --ignore=E203,E501,E266,F541,W503
        - '--exclude=tests/fixtures/*,pre-commit-sentinels/*'
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.3
  hooks:
    - id: check-github-workflows
      args: ["--verbose"]
- repo: local
  hooks:
    - id: foxylint-imports
      name: Import Modules not Names
      description: disallows the from_x_import_y import statement
      entry: foxylint-main imports
      language: python
      types: [python]
      args:
        - "--exclude=tests/fixtures/*.py"
        - "--exclude=pre-commit-sentinels/**/*.py"
        - "--accept=/from mylogging/"
    - id: foxylint-loggingcase
      name: Enforce lowercase logging
      description: do not capitalize sentences in log messages like you would in ordinary English
      entry: foxylint-main loggingcase
      language: python
      types: [python]
      args:
        - "--exclude=tests/fixtures/*.py"
    - id: yaml-not-yml
      name: YAML files must end with .yaml
      description: disallows the .yml suffix, allows only .yaml
      entry: foxylint-noyml
      language: python
      types: [file]
