name: Linters

on: pull_request

jobs:
  linters_and_formatters:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install poetry
        run:  curl -sSL https://install.python-poetry.org | python -
      - name: install myself
        run:  poetry install
      - name: Run linters etc
        run: |
          set -e
          poetry run pip install pre-commit
          poetry run pre-commit run --all-files
